backend:
  name: github
  repo: aarshkashy-cmd/Test # Make sure this matches your repo name
  branch: main

media_folder: "photo"
public_folder: "photo"

collections:
  - name: "gallery"
    label: "Gallery"
    folder: "photo"
    create: true
    fields:
      - {label: "Image Title", name: "title", widget: "string"}
      - {label: "Upload Photo", name: "image", widget: "image"}
